### PR TITLE
Magnific popup (again)

### PR DESCRIPTION
**Pull request by danilopopeye**
implement jglovier/gifs#22 :sparkles: 

screen shot 2014-03-03 at 16 04 24

### CODE REVIEW

**Comment by gjtorikian** [comment]
I was just looking for this as I got tired of opening each image in a new tab. What happened to this PR?

**Comment by jglovier** [comment]
>What happened to this PR?

@gjtorikian It fell off my radar. Honestly, the real challenge is that I can't easily contribute to this PR to get the styles I want because there's not easy way to checkout and commit to a branch that's in a fork. :confused:

**Comment by jglovier** [comment]
...also wasn't entirely convinced I wanted this behavior by default. I like being able to just click on the link and get the URL on the resulting load with a tap, then `cmd+L`, then `cmd+c`. This would make that harder, and remove some of the utility aspect of the index.

Plus, you can always preview gifs already in the corner preview box by hovering over any one of them.

**Comment by gjtorikian** [comment]
> Plus, you can always preview gifs already in the corner preview box by hovering over any one of them.

Oh dang. That's all I needed. Thanks!

**Comment by nullr1ver** [comment]
TBH, if you did implement this, you could have a url bar at the bottom that allows you to easily copy & paste the link to the gif

**Pull request closed without merging**
